/*
 * MainTestSuite.java
 * JUnit based test
 *
 * Created on 7 juin 2005, 11:20
 */

package com.exproxy.test;

import com.exproxy.tools.Logging;
import java.io.IOException;
import junit.framework.*;



/**
 *
 * @author David Crosson
 */
public class MainTestSuite extends TestCase {
    
    public MainTestSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("MainTestSuite");
        // True Tests
        suite.addTestSuite(EXProxyTest.class);
        
        // Tests to learn or try various API aspects
        suite.addTestSuite(JDKAPITest.class);
//        suite.addTestSuite(VariousSocketTest.class);
//        suite.addTestSuite(VariousSSLSocketTest.class);
//        suite.addTestSuite(VariousSSLLowLevelTest.class);
//        suite.addTestSuite(VariousHttpClientTest.class);
        return suite;
    }
    
    public static void main(String[] args) throws IOException {
        Logging.logSystemInit();
        junit.textui.TestRunner.run(suite());
    }
}
